### ISSUE TITLE
顶部导航栏的fragment里面空白

### ISSUE THREAD

**Issue by wenquanli** [ahuyangdong/TabCustom#1]
照着代码写了一遍 出现了顶部导航栏的fragment里面没有内容的情况 请问有什么解决办法吗

**Comment by ahuyangdong** [comment]
> 照着代码写了一遍 出现了顶部导航栏的fragment里面没有内容的情况 请问有什么解决办法吗

把“显示布局边界”调出来，看看是控件有没有显示，显示位置对不对，或者是属性设置错误导致无法在目标位置显示。
